import { getBlock } from "@/lib/blocks/catalog";
import { executionOrder, type Workflow } from "@/lib/workflow";
import { getNetwork, type NetworkConfig } from "@/lib/soroban/config";

/**
 * Generate a runnable Node.js script from a workflow using @stellar/stellar-sdk.
 *
 * This is a template-based generator: each block contributes a snippet, wired
 * in topological order. The output is meant to be readable, ownable code a
 * developer can drop into their own project — not a black box.
 */
export function generateJavaScript(wf: Workflow): string {
  const net = getNetwork(wf.meta.network);
  const steps = executionOrder(wf);

  const body = steps
    .map((node) => {
      const def = getBlock(node.type);
      if (!def) return `  // unknown block: ${node.type}`;
      return `  // ${def.label}\n${snippet(node.type, node.data, net)}`;
    })
    .join("\n\n");

  return `// Generated by Soroban Studio — "${wf.meta.name}"
// Network: ${net.label}
import {
  Keypair,
  Networks,
  Horizon,
  TransactionBuilder,
  Operation,
  Asset,
} from "@stellar/stellar-sdk";

const NETWORK_PASSPHRASE = "${net.networkPassphrase}";
const horizon = new Horizon.Server("${net.horizonUrl}");

async function main() {
${body || "  // (empty workflow)"}
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`;
}

function snippet(type: string, data: Record<string, unknown>, net: NetworkConfig): string {
  switch (type) {
    case "create-wallet":
      return `  const account = Keypair.random();
  console.log("Public key:", account.publicKey());${
    data.fund && net.friendbotUrl
      ? `\n  await fetch(\`${net.friendbotUrl}?addr=\${account.publicKey()}\`);`
      : net.friendbotUrl
        ? ""
        : `\n  // Fund this account manually on ${net.label} — no Friendbot available.`
  }`;
    case "send-payment":
      return `  // send ${data.amount ?? "?"} ${data.asset ?? "XLM"} to ${data.destination ?? "<dest>"}
  const src = await horizon.loadAccount(account.publicKey());
  const paymentTx = new TransactionBuilder(src, {
    fee: "100",
    networkPassphrase: NETWORK_PASSPHRASE,
  })
    .addOperation(Operation.payment({
      destination: ${js(data.destination)},
      asset: ${data.asset && data.asset !== "XLM" ? `new Asset(${js(data.asset)}, ISSUER)` : "Asset.native()"},
      amount: ${js(String(data.amount ?? "0"))},
    }))
    .setTimeout(30)
    .build();
  paymentTx.sign(account);
  const res = await horizon.submitTransaction(paymentTx);
  console.log("Payment tx:", res.hash);`;
    case "trigger-webhook":
      return `  await fetch(${js(data.url)}, {
    method: ${js(data.method ?? "POST")},
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ workflow: ${js(type)} }),
  });`;
    case "invoke-contract":
      return `  // Invoke Soroban contract ${data.contractId ?? "<contract>"}
  // Use rpc.Server + contract.call("${data.method ?? "method"}", ...args)
  console.log("invoke ${data.method ?? "method"} on", ${js(data.contractId)});`;
    case "loop-batch": {
      if (data.mode === "list") {
        const items = String(data.items ?? "")
          .split(/[,\n]/)
          .map((s) => s.trim())
          .filter(Boolean);
        return `  // Loop / Batch — repeat the next step for each item
  const items = ${js(items)};
  for (const [index, item] of items.entries()) {
    // TODO: run the next block here, using \`item\` / \`index\`
  }`;
      }
      return `  // Loop / Batch — repeat the next step
  const count = ${js(Number(data.count) || 0)};
  for (let index = 0; index < count; index++) {
    // TODO: run the next block here, using \`index\`
  }`;
    }
    default:
      return `  // TODO: implement ${type}`;
  }
}

function js(v: unknown): string {
  return JSON.stringify(v ?? "");
}
