import { getBlock } from "@/lib/blocks/catalog";
import { executionOrder, type Workflow, getDownstreamNodeIds } from "@/lib/workflow";
import { getNetwork, type NetworkConfig } from "@/lib/soroban/config";

/**
 * Generate a runnable Node.js script from a workflow using @stellar/stellar-sdk.
 *
 * This is a template-based generator: each block contributes a snippet, wired
 * in topological order. The output is meant to be readable, ownable code a
 * developer can drop into their own project — not a black box.
 */
export function generateJavaScript(wf: Workflow): string {
  const net = getNetwork(wf.meta.network);
  const steps = executionOrder(wf);

  const csvNode = wf.nodes.find((n) => n.type === "csv-import");
  const downstreamIds = csvNode ? getDownstreamNodeIds(wf, csvNode.id) : new Set<string>();

  const body = steps
    .map((node) => {
      const def = getBlock(node.type);
      if (!def) return `  // unknown block: ${node.type}`;
      
      let snip = snippet(node.type, node.data, net, wf);
      
      // Indent downstream blocks so they compile inside the csv-import loop
      if (downstreamIds.has(node.id)) {
        snip = snip
          .split("\n")
          .map((line) => "  " + line)
          .join("\n");
      }
      
      return `  // ${def.label}\n${snip}`;
    })
    .join("\n\n");

  const footer = csvNode ? "\n  }" : "";

  return `// Generated by Soroban Studio — "${wf.meta.name}"
// Network: ${net.label}
import {
  Keypair,
  Networks,
  Horizon,
  TransactionBuilder,
  Operation,
  Asset,
} from "@stellar/stellar-sdk";

const NETWORK_PASSPHRASE = "${net.networkPassphrase}";
const horizon = new Horizon.Server("${net.horizonUrl}");

async function main() {
${body || "  // (empty workflow)"}${footer}
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`;
}

function snippet(
  type: string,
  data: Record<string, unknown>,
  net: NetworkConfig,
  wf: Workflow
): string {
  const csvNode = wf.nodes.find((n) => n.type === "csv-import");
  const mappings = (csvNode?.data?.mappings as Record<string, string>) || {};

  switch (type) {
    case "create-wallet":
      return `  const account = Keypair.random();
  console.log("Public key:", account.publicKey());${
    data.fund && net.friendbotUrl
      ? `\n  await fetch(\`${net.friendbotUrl}?addr=\${account.publicKey()}\`);`
      : net.friendbotUrl
        ? ""
        : `\n  // Fund this account manually on ${net.label} — no Friendbot available.`
  }`;

    case "csv-import":
      return `  const csvData = \`${(data.csvData as string ?? "").replace(/`/g, "\\`").replace(/\${/g, "\\${")}\`;
  const mappings = ${JSON.stringify(mappings)};
  
  const parseLine = (line) => {
    const result = [];
    let current = "";
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === '"' || char === "'") {
        inQuotes = !inQuotes;
      } else if (char === ',' && !inQuotes) {
        result.push(current.trim());
        current = "";
      } else {
        current += char;
      }
    }
    result.push(current.trim());
    return result;
  };

  const lines = csvData.split("\\n").map(l => l.trim()).filter(Boolean);
  const headers = lines.length > 0 ? parseLine(lines[0]) : [];
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    const cols = parseLine(lines[i]);
    const row = {};
    headers.forEach((h, idx) => {
      row[h] = cols[idx] || "";
    });
    rows.push(row);
  }

  console.log(\`Loaded \${rows.length} rows from CSV\`);
  for (const row of rows) {
    const destination = row[mappings.destination];
    const amount = row[mappings.amount];
    const memo = row[mappings.memo];
    const contractId = row[mappings.contractId];
    const address = row[mappings.address];
    console.log(\`Processing row: destination=\${destination}, amount=\${amount}\`);`;

    case "send-payment": {
      const dest = mappings.destination ? "destination" : js(data.destination);
      const amt = mappings.amount ? "amount" : js(String(data.amount ?? "0"));
      return `  // send ${data.amount ?? "?"} ${data.asset ?? "XLM"} to ${data.destination ?? "<dest>"}
  const src = await horizon.loadAccount(account.publicKey());
  const paymentTx = new TransactionBuilder(src, {
    fee: "100",
    networkPassphrase: NETWORK_PASSPHRASE,
  })
    .addOperation(Operation.payment({
      destination: ${dest},
      asset: ${data.asset && data.asset !== "XLM" ? `new Asset(${js(data.asset)}, ISSUER)` : "Asset.native()"},
      amount: ${amt},
    }))
    .setTimeout(30)
    .build();
  paymentTx.sign(account);
  const res = await horizon.submitTransaction(paymentTx);
  console.log("Payment tx:", res.hash);`;
    }

    case "trigger-webhook": {
      const url = mappings.url ? "url" : js(data.url);
      return `  await fetch(${url}, {
    method: ${js(data.method ?? "POST")},
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ workflow: ${js(type)} }),
  });`;
    }

    case "invoke-contract": {
      const cid = mappings.contractId ? "contractId" : js(data.contractId);
      return `  // Invoke Soroban contract ${data.contractId ?? "<contract>"}
  // Use rpc.Server + contract.call("${data.method ?? "method"}", ...args)
  console.log("invoke ${data.method ?? "method"} on", ${cid});`;
    }

    default:
      return `  // TODO: implement ${type}`;
  }
}

function js(v: unknown): string {
  return JSON.stringify(v ?? "");
}
