import { getBlock } from "@/lib/blocks/catalog";
import { type Workflow } from "@/lib/workflow";

/**
 * Generate a Soroban smart-contract (Rust) skeleton from a workflow.
 *
 * Contract-category blocks (invoke/deploy/verify + confidential transfer) map
 * to contract functions; off-chain blocks are emitted as doc comments so the
 * exported crate stays a faithful description of the whole flow. Pair this with
 * the JavaScript export for the client side.
 */
export function generateRust(wf: Workflow): string {
  const contractBlocks = wf.nodes.filter(
    (n) => getBlock(n.type)?.category === "contract"
  );

  const fns = contractBlocks
    .map((n) => {
      const def = getBlock(n.type)!;
      const fnName = (n.data.method as string) || def.type.replace(/-/g, "_");
      return `    /// ${def.label} — ${def.description}
    pub fn ${sanitizeIdent(fnName)}(env: Env) -> Symbol {
        // TODO: implement ${def.label}
        symbol_short!("ok")
    }`;
    })
    .join("\n\n");

  const offchain = wf.nodes
    .filter((n) => getBlock(n.type)?.category !== "contract")
    .map((n) => `//   - ${getBlock(n.type)?.label ?? n.type} (off-chain / client-side)`)
    .join("\n");

  return `#![no_std]
// Generated by Soroban Studio — "${wf.meta.name}"
//
// On-chain steps are exposed as contract functions below.
// Off-chain steps run in the generated JavaScript client:
${offchain || "//   (none)"}

use soroban_sdk::{contract, contractimpl, symbol_short, Env, Symbol};

#[contract]
pub struct WorkflowContract;

#[contractimpl]
impl WorkflowContract {
${fns || "    // No on-chain contract blocks in this workflow."}
}
`;
}

function sanitizeIdent(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_]/g, "_");
  return /^[0-9]/.test(cleaned) ? `f_${cleaned}` : cleaned;
}
